# Form implementation generated from reading ui file '.\templates\dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(400, 300)
        dlgCalendar.setMinimumSize(QtCore.QSize(400, 300))
        dlgCalendar.setMaximumSize(QtCore.QSize(400, 300))
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=dlgCalendar)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.calendarWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.calendarWidget.setMaximumSize(QtCore.QSize(400, 300))
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Dialog"))
