# Form implementation generated from reading ui file '.\templates\venCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_venCalendar(object):
    def setupUi(self, venCalendar):
        venCalendar.setObjectName("venCalendar")
        venCalendar.resize(400, 300)
        venCalendar.setMinimumSize(QtCore.QSize(400, 300))
        venCalendar.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        venCalendar.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=venCalendar)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.calendar.setMinimumSize(QtCore.QSize(391, 251))
        self.calendar.setMaximumSize(QtCore.QSize(391, 251))
        self.calendar.setGridVisible(True)
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendar.setObjectName("calendar")
        venCalendar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=venCalendar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        venCalendar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=venCalendar)
        self.statusbar.setObjectName("statusbar")
        venCalendar.setStatusBar(self.statusbar)

        self.retranslateUi(venCalendar)
        QtCore.QMetaObject.connectSlotsByName(venCalendar)

    def retranslateUi(self, venCalendar):
        _translate = QtCore.QCoreApplication.translate
        venCalendar.setWindowTitle(_translate("venCalendar", "Calendar"))
